version: '3'
services:
    mkadiri-golang-microservice:
        image: mkadiri/golang-microservice
        container_name: mkadiri-golang-microservice
        environment:
            - MYSQL_HOST=mkadiri-mysql
            - MYSQL_PORT=3306
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=mkadiri_golang_microservice
            - CORS_ALLOWED_ORIGINS=*
            - MODE=DEV
        ports:
            - 8181:8000
        restart: always
    mkadiri-mysql:
        image: mysql
        container_name: mkadiri-mysql
        ports:
            - 3307:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
        command: --default-authentication-plugin=mysql_native_password
        restart: always
